
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: smileup_db
    restart: always
    environment:
      POSTGRES_DB: smileup_db
      POSTGRES_PASSWORD: smileup_password
      POSTGRES_USER: smileup_user
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "smileup_db", "-U", "smileup_user"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
